### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by tjulises** [SergioVenicio21/music-player#20]
Hey,  @SergioVenicio21     I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by SergioVenicio21** [comment]
Very good.
You can get in contact by email sergiovenicio2015@gmail.com

**Comment by tjulises** [comment]
@SergioVenicio21 
Yes of course
I have some questions:

What's the name that should be displayed on the logo/icon ?

What's the purpose/goal of this project ? (details of the project can work too)

What's the message you would like the logo/icon to transmit?

I'll be looking forward to your reply! hopefully something good can come out of this work!

**Comment by SergioVenicio21** [comment]
What's the name that should be displayed on the logo/icon ?
Music-Player

What's the purpose/goal of this project ? (details of the project can work too)
This project is a web music player to work in local network

What's the message you would like the logo/icon to transmit?
I really don't know
